kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  namespace: moserblog
  annotations:
    volume.beta.kubernetes.io/storage-class: mssql-azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi